name: Deploy static content to Pages

on:
  push:
<<<<<<< HEAD
    branches: ['main']
=======
    branches: ['main', 'master']
>>>>>>> 1f7fbad1c4a894891b963d59e791fd52b650b25d

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
<<<<<<< HEAD
      - name: Build
        run: npm run build
=======
      - name: Build WeWeb
        run: npm run build -w WeWeb
>>>>>>> 1f7fbad1c4a894891b963d59e791fd52b650b25d
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
<<<<<<< HEAD
          path: './dist'
=======
          path: './WeWeb/dist'
>>>>>>> 1f7fbad1c4a894891b963d59e791fd52b650b25d
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
